# -*- coding: utf-8 -*-
"""WebCrawler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fUrYChQr5tzmIY3ADb6K6cEULewHQnHj
"""

!pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup

def web_crawler(query):
    print(f"Searching for: {query}\n")

    url = f"https://html.duckduckgo.com/html/?q={query}"

    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    results = []

    for result in soup.find_all("a", class_="result__a", limit=10):
        title = result.text
        link = result.get("href")

        results.append({
            "title": title,
            "link": link
        })

    return results


# Test
data = web_crawler("Digital Marketing services in mumbai")

for i, item in enumerate(data, 1):
    print(f"{i}. {item['title']}")
    print(f"   {item['link']}\n")

import json

with open("leads.json", "w") as file:
    json.dump(data, file, indent=4)

print("Data saved to leads.json")